export default [
    {
        board_id : 0,
        title : "공지사항입니다",
        content : "이것은 공지사항입니다! 참고해주시기 바랍니다.",
        user_id : "admin",
        tag : "notice",
        start_date : "2022-01-19",
        end_date : "2022-01-19",
        likes : 1,
        hit : 1,
    },
    {
        board_id : 1,
        title : "공지사항 작성 방법",
        content : "이것은 공지사항 작성방법입니다! 내용 확인 후 참고해주시기 바랍니다.",
        user_id : "ssafy",
        tag : "notice",
        start_date : "2022-01-18",
        end_date : "2022-01-19",
        likes : 5,
        hit : 3,
    },
    {
        board_id : 2,
        title : "싸피사만코 이용 안내",
        content : "이것은 싸피사만코 이용 안내입니다! 내용 확인 후 참고해주시기 바랍니다.",
        user_id : "ssafy",
        tag : "notice",
        start_date : "2022-01-17",
        end_date : "2022-01-19",
        likes : 5,
        hit : 3,
    },
    {
        board_id : 3,
        title : "공지사항입니다",
        content : "이것은 공지사항입니다! 참고해주시기 바랍니다.",
        user_id : "admin",
        tag : "notice",
        start_date : "2022-01-19",
        end_date : "2022-01-19",
        likes : 1,
        hit : 1,
    },
    {
        board_id : 4,
        title : "공지사항 작성 방법",
        content : "이것은 공지사항 작성방법입니다! 내용 확인 후 참고해주시기 바랍니다.",
        user_id : "ssafy",
        tag : "notice",
        start_date : "2022-01-18",
        end_date : "2022-01-19",
        likes : 5,
        hit : 3,
    },
    {
        board_id : 5,
        title : "싸피사만코 이용 안내",
        content : "이것은 싸피사만코 이용 안내입니다! 내용 확인 후 참고해주시기 바랍니다.",
        user_id : "ssafy",
        tag : "notice",
        start_date : "2022-01-17",
        end_date : "2022-01-19",
        likes : 5,
        hit : 3,
    },
    {
        board_id : 6,
        title : "공지사항입니다",
        content : "이것은 공지사항입니다! 참고해주시기 바랍니다.",
        user_id : "admin",
        tag : "notice",
        start_date : "2022-01-19",
        end_date : "2022-01-19",
        likes : 1,
        hit : 1,
    },
    {
        board_id : 7,
        title : "공지사항 작성 방법",
        content : "이것은 공지사항 작성방법입니다! 내용 확인 후 참고해주시기 바랍니다.",
        user_id : "ssafy",
        tag : "notice",
        start_date : "2022-01-18",
        end_date : "2022-01-19",
        likes : 5,
        hit : 3,
    },
    {
        board_id : 8,
        title : "싸피사만코 이용 안내",
        content : "이것은 싸피사만코 이용 안내입니다! 내용 확인 후 참고해주시기 바랍니다.",
        user_id : "ssafy",
        tag : "notice",
        start_date : "2022-01-17",
        end_date : "2022-01-19",
        likes : 5,
        hit : 3,
    },
    {
        board_id : 9,
        title : "공지사항입니다",
        content : "이것은 공지사항입니다! 참고해주시기 바랍니다.",
        user_id : "admin",
        tag : "notice",
        start_date : "2022-01-19",
        end_date : "2022-01-19",
        likes : 1,
        hit : 1,
    },
    {
        board_id : 10,
        title : "공지사항 작성 방법",
        content : "이것은 공지사항 작성방법입니다! 내용 확인 후 참고해주시기 바랍니다.",
        user_id : "ssafy",
        tag : "notice",
        start_date : "2022-01-18",
        end_date : "2022-01-19",
        likes : 5,
        hit : 3,
    },
    {
        board_id : 11,
        title : "싸피사만코 이용 안내",
        content : "이것은 싸피사만코 이용 안내입니다! 내용 확인 후 참고해주시기 바랍니다.",
        user_id : "ssafy",
        tag : "notice",
        start_date : "2022-01-17",
        end_date : "2022-01-19",
        likes : 5,
        hit : 3,
    },
    {
        board_id : 12,
        title : "공지사항입니다",
        content : "이것은 공지사항입니다! 참고해주시기 바랍니다.",
        user_id : "admin",
        tag : "notice",
        start_date : "2022-01-19",
        end_date : "2022-01-19",
        likes : 1,
        hit : 1,
    },
    {
        board_id : 13,
        title : "공지사항 작성 방법",
        content : "이것은 공지사항 작성방법입니다! 내용 확인 후 참고해주시기 바랍니다.",
        user_id : "ssafy",
        tag : "notice",
        start_date : "2022-01-18",
        end_date : "2022-01-19",
        likes : 5,
        hit : 3,
    },
    {
        board_id : 14,
        title : "싸피사만코 이용 안내",
        content : "이것은 싸피사만코 이용 안내입니다! 내용 확인 후 참고해주시기 바랍니다.",
        user_id : "ssafy",
        tag : "notice",
        start_date : "2022-01-17",
        end_date : "2022-01-19",
        likes : 5,
        hit : 3,
    },
    {
        board_id : 15,
        title : "공지사항입니다",
        content : "이것은 공지사항입니다! 참고해주시기 바랍니다.",
        user_id : "admin",
        tag : "notice",
        start_date : "2022-01-19",
        end_date : "2022-01-19",
        likes : 1,
        hit : 1,
    },  
]