export default [
    {
        board_id : 0,
        title : "공지사항입니다",
        content : "이것은 공지사항입니다! 참고해주시기 바랍니다.",
        user_id : "admin",
        tag : "notice",
        start_date : "2022-01-19",
        end_date : "2022-01-19",
        likes : 1,
        hit : 1,
    },
    {
        board_id : 1,
        title : "공지사항 작성 방법",
        content : "이것은 공지사항 작성방법입니다! 내용 확인 후 참고해주시기 바랍니다.",
        user_id : "ssafy",
        tag : "notice",
        start_date : "2022-01-18",
        end_date : "2022-01-19",
        likes : 5,
        hit : 8,
    },
    {
        board_id : 2,
        title : "싸피사만코 이용 안내",
        content : "이것은 싸피사만코 이용 안내입니다! 내용 확인 후 참고해주시기 바랍니다.",
        user_id : "ssafy",
        tag : "notice",
        start_date : "2022-01-17",
        end_date : "2022-01-19",
        likes : 5,
        hit : 39,
    },
    {
        board_id : 3,
        title : "공지사항입니다",
        content : "이것은 공지사항입니다! 참고해주시기 바랍니다.",
        user_id : "admin",
        tag : "notice",
        start_date : "2022-01-19",
        end_date : "2022-01-19",
        likes : 1,
        hit : 7,
    },
    {
        board_id : 4,
        title : "공지사항 작성 방법",
        content : "이것은 공지사항 작성방법입니다! 내용 확인 후 참고해주시기 바랍니다.",
        user_id : "ssafy",
        tag : "notice",
        start_date : "2022-01-18",
        end_date : "2022-01-19",
        likes : 5,
        hit : 35,
    },
    {
        board_id : 5,
        title : "싸피사만코 이용 안내",
        content : "이것은 싸피사만코 이용 안내입니다! 내용 확인 후 참고해주시기 바랍니다.",
        user_id : "ssafy",
        tag : "notice",
        start_date : "2022-01-17",
        end_date : "2022-01-19",
        likes : 27,
        hit : 118,
    },
    {
        board_id : 6,
        title : "공지사항입니다",
        content : "이것은 공지사항입니다! 참고해주시기 바랍니다.",
        user_id : "admin",
        tag : "notice",
        start_date : "2022-01-19",
        end_date : "2022-01-19",
        likes : 1,
        hit : 1,
    },
    {
        board_id : 7,
        title : "공지사항 작성 방법",
        content : "이것은 공지사항 작성방법입니다! 내용 확인 후 참고해주시기 바랍니다.",
        user_id : "ssafy",
        tag : "notice",
        start_date : "2022-01-18",
        end_date : "2022-01-19",
        likes : 5,
        hit : 12,
    },
    {
        board_id : 8,
        title : "싸피사만코 이용 안내",
        content : "이것은 싸피사만코 이용 안내입니다! 내용 확인 후 참고해주시기 바랍니다.",
        user_id : "ssafy",
        tag : "notice",
        start_date : "2022-01-17",
        end_date : "2022-01-19",
        likes : 6,
        hit : 27,
    },
    {
        board_id : 9,
        title : "공지사항입니다",
        content : "이것은 공지사항입니다! 참고해주시기 바랍니다.",
        user_id : "admin",
        tag : "notice",
        start_date : "2022-01-19",
        end_date : "2022-01-19",
        likes : 10,
        hit : 50,
    },
    {
        board_id : 10,
        title : "공지사항 작성 방법",
        content : "이것은 공지사항 작성방법입니다! 내용 확인 후 참고해주시기 바랍니다.",
        user_id : "ssafy",
        tag : "notice",
        start_date : "2022-01-18",
        end_date : "2022-01-19",
        likes : 5,
        hit : 37,
    },
    {
        board_id : 11,
        title : "싸피사만코 이용 안내",
        content : "이것은 싸피사만코 이용 안내입니다! 내용 확인 후 참고해주시기 바랍니다.",
        user_id : "ssafy",
        tag : "notice",
        start_date : "2022-01-17",
        end_date : "2022-01-19",
        likes : 1,
        hit : 29,
    },
    {
        board_id : 12,
        title : "공지사항입니다",
        content : "이것은 공지사항입니다! 참고해주시기 바랍니다.",
        user_id : "admin",
        tag : "notice",
        start_date : "2022-01-19",
        end_date : "2022-01-19",
        likes : 0,
        hit : 1,
    },
    {
        board_id : 13,
        title : "공지사항 작성 방법",
        content : "이것은 공지사항 작성방법입니다! 내용 확인 후 참고해주시기 바랍니다.",
        user_id : "ssafy",
        tag : "notice",
        start_date : "2022-01-18",
        end_date : "2022-01-19",
        likes : 2,
        hit : 3,
    },
    {
        board_id : 14,
        title : "싸피사만코 이용 안내",
        content : "이것은 싸피사만코 이용 안내입니다! 내용 확인 후 참고해주시기 바랍니다.",
        user_id : "ssafy",
        tag : "notice",
        start_date : "2022-01-17",
        end_date : "2022-01-19",
        likes : 0,
        hit : 0,
    },
    {
        board_id : 15,
        title : "----------공지사항---------",
        content : "이것은 공지사항입니다! 참고해주시기 바랍니다.",
        user_id : "admin",
        tag : "notice",
        start_date : "2022-01-19",
        end_date : "2022-01-19",
        likes : 12,
        hit : 18,
    },  
    {
        board_id : 16,
        title : "질문게시판 이용 방법",
        content : "이것은 질문게시판 이용방법 안내입니다! 내용 확인 후 참고해주시기 바랍니다.",
        user_id : "ssafy",
        tag : "qna",
        start_date : "2022-01-18",
        end_date : "2022-01-19",
        likes : 62,
        hit : 90,
    },
    {
        board_id : 17,
        title : "질문있어요",
        content : "싸피사만코에 대해 질문있습니다",
        user_id : "ssafy",
        tag : "qna",
        start_date : "2022-01-17",
        end_date : "2022-01-19",
        likes : 17,
        hit : 35,
    },
    {
        board_id : 18,
        title : "스터디 어떻게 만드나요?",
        content : "스터디 어떻게 만드는지 알려 주실 분 있나요?",
        user_id : "ekdus627",
        tag : "qna",
        start_date : "2022-01-19",
        end_date : "2022-01-19",
        likes : 5,
        hit : 18,
    },  
    {
        board_id : 19,
        title : "자유게시한",
        content : "이것은 자유게시판 입니다.",
        user_id : "ssafy",
        tag : "free",
        start_date : "2022-01-17",
        end_date : "2022-01-19",
        likes : 17,
        hit : 35,
    },
    {
        board_id : 20,
        title : "저랑 스터디 하실분~~",
        content : "알고리즘 스터디를 하려고 하는데 같이 하실 분 있나요?",
        user_id : "ekdus627",
        tag : "free",
        start_date : "2022-01-19",
        end_date : "2022-01-19",
        likes : 5,
        hit : 18,
    },  
]